image: barichello/godot-ci:3.2

stages:
    - build
    - release

build:
    stage: build
    script:
        - ./build.sh
    artifacts:
        paths:
            - dist

pages:
    stage: release
    dependencies:
        - build
    script:
        - mv dist public
    artifacts:
        paths:
            - public

