image: barichello/godot-ci:3.2

stages:
    - build
    - release

build:
    stage: build
    script:
        - ./build.sh
    artifacts:
        paths:
            - dist

build-ggj-release:
    stage: build
    script:
        - ./build-ggj-release.sh
    artifacts:
        paths:
            - super-repair-bros-ggj2020.zip

pages:
    stage: release
    dependencies:
        - build
    script:
        - mv dist public
    artifacts:
        paths:
            - public

